# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c7b02cfe48f4fdd714fcb6e35923ffa9"
name = "Max-Staging"
application_url = "https://max-staging.solnix.store"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test321-8746.myshopify.com"

[webhooks]
api_version = "2026-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://max-staging.solnix.store/api/webhooks"
  customer_data_request_url = "https://max-staging.solnix.store/api/webhooks"
  shop_deletion_url = "https://max-staging.solnix.store/api/webhooks"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://max-staging.solnix.store/api/auth/callback"
]
