# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c7b02cfe48f4fdd714fcb6e35923ffa9"
name = "Max-Staging"
application_url = "https://gbf5co37alo6y8n04rqa49cm.91.239.208.85.sslip.io"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test321-8746.myshopify.com"

[webhooks]
api_version = "2025-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://gbf5co37alo6y8n04rqa49cm.91.239.208.85.sslip.io/api/webhooks"
  customer_data_request_url = "https://gbf5co37alo6y8n04rqa49cm.91.239.208.85.sslip.io/api/webhooks"
  shop_deletion_url = "https://gbf5co37alo6y8n04rqa49cm.91.239.208.85.sslip.io/api/webhooks"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://gbf5co37alo6y8n04rqa49cm.91.239.208.85.sslip.io/api/auth/callback"
]
