# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
# IMPORTANT: Fill in client_id and application_url from your new Shopify Partner Dashboard app

name = "Snap Compare"
client_id = "d70acf1632992522daae7af3dfb25af1"
application_url = "https://atzb1ruma6ra252uivl7a865.91.239.208.85.sslip.io"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "https://atzb1ruma6ra252uivl7a865.91.239.208.85.sslip.io/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://atzb1ruma6ra252uivl7a865.91.239.208.85.sslip.io/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
